server:
  port: 8088

app:
  id: demo-springboot # 应用id,与Apollo中创建的保持一致

apollo:
  meta: http://47.97.104.107:8080 # Apollo Meta服务地址
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
  admin-url: http://47.97.104.107:8090
  app-id: demo-springboot
  cluster: default
  namespace: application
  token: 1e0d0b0b0a0b0c0d0e0f0g0h0i0j

rocketmq:
  name-server: localhost:9876
  producer:
    group: GID-AOI-WORKBENCH
