server:
  port: 8088

app:
  id: demo-springboot # 应用id,与Apollo中创建的保持一致

apollo:
  meta: http://47.97.104.107:8080 # Apollo Meta服务地址
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
  admin-url: http://47.97.104.107:8090
  app-id: demo-springboot
  env: DEV
  cluster: default
  namespace: application
  token: 660b6876835cdaaf28cb346261d8479ede4696d1